---
title: "condor_flowjo_workflow - v0.1.3"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{condor_flowjo_workflow}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  markdown: 
    wrap: 72
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(condor)
library(flowWorkspace)
library(CytoML)
library(Biobase)
library(ggplot2)
```

## Read the .wsp file
```{r}
ws <- open_flowjo_xml("../.test_files/flowjo_workspace.wsp")

ws
```

## Transformation into **gatingset** object
```{r}
gs <- flowjo_to_gatingset(ws, name = "samples", path = "../.test_files/fcs_flowjo_ws/")

gs
```

### Visualization of the gating strategy
```{r}
plot(gs, bool = TRUE)
```

### Get unique gate names
```{r}
gs_pop_get_stats(gs)
```

```{r}
nodelist <- gs_get_pop_paths(gs, path = "auto")
nodelist
```

## Prepare the data
```{r}
fc_data <- prep_fjw(data_gs = gs, 
                   pop = "root", 
                   gate_list = nodelist, 
                   inverse.transform = TRUE,
                   transformation = "a",
                   remove_param = "FSC-A")

class(fc_data) # The structure of this list is compatible with my other analysis pipeline and can be directly used for downstream analysis
```

### Does it work
I will subset the sample to see if the gating gets translated correctly in this new dataframe
```{r}
set.seed(91)

tmp <- cbind(fc_data$expr$orig, fc_data$anno$cell_anno)

tmp <- tmp[sample(1:dim(tmp)[1], 100000), ]
```

```{r}
ggplot(tmp[tmp$`CD45+` == 1,], aes(x= `CD19`, y = `CD3`, color = as.factor(`CD19+`))) +
  geom_point() + 
  theme_bw() + 
  theme(aspect.ratio = 1) + 
  scale_color_viridis_d()
```

```{r}
rm(tmp)
```

# Session Info
```{r}
info <- sessionInfo()

info
```
