#' learnUMAP
#'
#' @title learnUMAP
#' @description Uses the model calculated with *runUMAP* to project new samples
#' @param fcd flow cytometry dataset.
#' @param input_type data to use for the calculation of the UMAP, e.g. "expr" or "pca".
#' @param data_slot name of the PCA data slot to use to harmonize. If no prefix was added the, *orig*.
#' @param model Data associated with an existing embedding.
#' @param n_epochs Number of epochs to use during the optimization of the embedded coordinates. A value between 30 - 100 is a reasonable trade off between speed and thoroughness. By default, this value is set to one third the number of epochs used to build the model.
#' @param prefix Prefix for the name of the dimensionality reduction.
#' @param n_threads Number of threads to use, (except during stochastic gradient descent). Default is half the number of concurrent threads supported by the system.
#' @param seed A seed is set for reproducibility.
#' @return learnUMAP
#'
#' @export
learnUMAP <- function(fcd,
                      input_type,
                      data_slot,
                      model,
                      n_epochs = 100,
                      prefix = NULL,
                      n_threads = 32,
                      seed = 91) {

  set.seed(seed)

  umapMat <- uwot::umap_transform(X = fcd[[input_type]][[data_slot]],
                                  model = model,
                                  n_epochs = n_epochs,
                                  n_threads = n_threads)

  colnames(umapMat) <- c("UMAP1", "UMAP2")

  umap_name <- sub("^_", "" , paste(prefix, input_type, data_slot, sep = "_"))

  fcd[["umap"]][[umap_name]] <- umapMat

  return(fcd)

}

#' train_transfer_model
#'
#' @title train_transfer_model
#' @description Train a machine learning model to transfer cell label (this function implement the *caret* workflow)
#' @param fcd flow cytometry dataset.
#' @param input_type data to use for the calculation of the UMAP, e.g. "expr" or "pca".
#' @param data_slot name of the PCA data slot to use to harmonize. If no prefix was added the, *orig*.
#' @param label Vector with the labels to be used for the label transfer.
#' @param method A string specifying which classification or regression model to use. Possible values are found using names(getModelInfo()). See http://topepo.github.io/caret/train-models-by-tag.html. A list of functions can also be passed for a custom model function. See http://topepo.github.io/caret/using-your-own-model-in-train.html for details.
#' @param tuneLength An integer denoting the amount of granularity in the tuning parameter grid. By default, this argument is the number of levels for each tuning parameters that should be generated by train. If trainControl has the option search = "random", this is the maximum number of tuning parameter combinations that will be generated by the random search. (NOTE: If given, this argument must be named.)
#' @param trControl A list of values that define how this function acts. See trainControl and http://topepo.github.io/caret/using-your-own-model-in-train.html. (NOTE: If given, this argument must be named.)
#' @param seed A seed is set for reproducibility.
#' @import caret
#' @import randomForest
#' @return train_transfer_model
#'
#' @export
train_transfer_model <- function(fcd,
                                 input_type,
                                 data_slot,
                                 label,
                                 method = "knn",
                                 tuneLength = 5,
                                 trControl = trainControl(method = "cv"),
                                 seed = 91) {

  container <- list()

  set.seed(seed)

  model <- train(x = fcd[[input_type]][[data_slot]],
                 y = factor(label),
                 method = method,
                 tuneLength = tuneLength,
                 trControl = trControl)

  performance <- ggplot(model) +
    geom_errorbar(data = model$results, aes(ymin = Accuracy - AccuracySD, ymax = Accuracy + AccuracySD), width = 0.4) +
    theme_classic(base_size = 15)

  features <- plot(varImp(model))

  container[["lt_model"]] <- model
  container[["performace_plot"]] <- performance
  container[["features_plot"]] <- features

  fcd[["extras"]][["lt_model"]] <- container

  return(fcd)
}

#' predict_labels
#'
#' @title predict_labels
#' @description Uses the model generated with *train_transfer_model* to predict the labels of new samples
#' @param fcd flow cytometry dataset.
#' @param input_type data to use for the calculation of the UMAP, e.g. "expr" or "pca".
#' @param data_slot name of the PCA data slot to use to harmonize. If no prefix was added the, *orig*.
#' @param model_object Caret model to the used for the label transfer.
#' @param label Label for the output column of the condor object.
#' @param seed A seed is set for reproducibility.
#' @return predict_labels
#'
#' @export
predict_labels <- function(fcd,
                           input_type,
                           data_slot,
                           model_object,
                           label = "predicted_labels",
                           seed = 91) {

  set.seed(seed)

  fcd[["clustering"]][[label]] <- data.frame(Description = "predicted",
                                             predicted_label = predict(model_object$extras$lt_model$lt_model,
                                                                       newdata = fcd[[input_type]][[data_slot]]))

  return(fcd)

}
